full pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -208,9 +208,6 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-
-      - destroy-environment:
-          workflowId: ${CIRCLE_WORKFLOW_ID:0:7}
       - notify-onfail
       - notify-onsuccess
 
@@ -231,8 +228,6 @@ jobs:
             cd .circleci/ansible
             cat inventory.txt
             ansible-playbook -i ~/project/.circleci/ansible/inventory.txt configure-server.yml
-      - destroy-environment:
-          workflowId: ${CIRCLE_WORKFLOW_ID:0:7}
 
       - notify-onfail
       - notify-onsuccess
@@ -266,10 +261,6 @@ jobs:
           name: saving value
           command: |  
               curl -X POST https://keyvalue.immanuel.co/api/KeyVal/UpdateValue/${kvbd_key}/migration_${CIRCLE_WORKFLOW_ID:0:7}/1 -d "content-length: 4"
-      - revert-migrations:
-          workflowId: ${CIRCLE_WORKFLOW_ID:0:7}
-      - destroy-environment:
-          workflowId: ${CIRCLE_WORKFLOW_ID:0:7}
       - notify-onfail
       - notify-onsuccess
 
@@ -305,12 +296,10 @@ jobs:
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
       - notify-onfail
       - notify-onsuccess
-      - destroy-environment
-      - revert-migrations
                     
   deploy-backend:
     docker:
-      - image: cimg/base:stable #cimg/deploy:2022.11.1-node #cimg/base:stable
+      - image: cimg/base:stable 
     steps:
       - checkout
       - install_node_npm
@@ -338,7 +327,6 @@ jobs:
             cd backend
             npm run build
       - run:
-          # dist/* package*
           name: packaging backend files
           command: |
             cd backend
@@ -348,15 +336,7 @@ jobs:
             cp ./backend/artifact.tar.gz ./.circleci/ansible/roles/deploy/files
       
 
-      # # --------- to be removed --------------
-      # - run:
-      #     name: Add back-end ip to ansible inventory
-      #     command: |       
-      #       aws ec2 describe-instances \
-      #       --query 'Reservations[*].Instances[*].PublicIpAddress' \
-      #       --filters "Name=tag:Name,Values=backend-5096119" \
-      #       --output text >> .circleci/ansible/inventory.txt 
-      # # --------- to be removed --------------
+
 
 
       - run:
@@ -368,8 +348,6 @@ jobs:
 
       - notify-onfail
       - notify-onsuccess
-      # - destroy-environment
-      # - revert-migrations
 
 
   smoke-test:
@@ -379,38 +357,38 @@ jobs:
       - checkout
       - install_awscli
 
-      # - run:
-      #     name: Backend smoke test.
-      #     command: |
-      #         BACKEND_IP=$(aws ec2 describe-instances \
-      #           --query 'Reservations[*].Instances[*].PublicIpAddress' \
-      #           --filters "Name=tag:Name,Values=backend-"${CIRCLE_WORKFLOW_ID:0:7}"" \
-      #           --output text)
+      - run:
+          name: Backend smoke test.
+          command: |
+              BACKEND_IP=$(aws ec2 describe-instances \
+                --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                --filters "Name=tag:Name,Values=backend-"${CIRCLE_WORKFLOW_ID:0:7}"" \
+                --output text)
                 
-      #         export API_URL="http://${BACKEND_IP}:3030"
-      #         echo "${API_URL}"
-      #         if curl "${API_URL}/api/status" | grep "ok"
-      #         then
-      #             exit 0
-      #         else
-      #             exit 1
-      #         fi
-      # - run:
-      #     name: Frontend smoke test.
-      #     command: |
-      #         URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"                          
-      #         echo ${URL} 
-      #         if curl -s ${URL} | grep "Welcome"
-      #         then
-      #             # Change this to 0 after the job fails
-      #           exit 1
-      #         else
-      #           exit 1
-      #         fi
+              export API_URL="http://${BACKEND_IP}:3030"
+              echo "${API_URL}"
+              if curl "${API_URL}/api/status" | grep "ok"
+              then
+                  exit 0
+              else
+                  exit 1
+              fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"                          
+              echo ${URL} 
+              if curl -s ${URL} | grep "Welcome"
+              then
+                  # Change this to 0 after the job fails
+                exit 1
+              else
+                exit 1
+              fi
     
       
-      # - destroy-environment
-      # - revert-migrations
+      - destroy-environment
+      - revert-migrations
       - notify-onfail
       - notify-onsuccess
 
@@ -418,6 +396,7 @@ jobs:
     docker:
       - image: cimg/base:stable
     steps:
+      - checkout
       - install_awscli
       - run:
           name: Update cloudfront distribution
@@ -427,8 +406,8 @@ jobs:
             --stack-name InitialStack \
             --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
             --tags project=udapeople
-      # - destroy-environment
-      # - revert-migrations
+      - destroy-environment
+      - revert-migrations
       - notify-onfail
       - notify-onsuccess
 
@@ -440,14 +419,22 @@ jobs:
           name: Get old stack workflow id
           command: |
               # your code here
-              export OldWorkflowID="the id here"
-              export STACKS=[] #put the list of stacks here
+              export OldWorkflowID=$(aws cloudformation \
+              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
+              echo OldWorkflowID: "${OldWorkflowID}"
+              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+              --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+              echo Stack names: "${STACKS[@]}"
       - run:
           name: Remove old stacks and files
           command: |
                 if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
                 then
-
+                    aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+                    aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+                    aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
                 fi
             
 
@@ -481,5 +468,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
+      - cleanup:
+          requires: [cloudfront-update]
